### PR TITLE
Enhancement: Merged all offline functions in one module.

### LINKED ISSUE #185: Enhancement: Merging all the offline functions in one module
### Creating a single module for all the offline working function.
- [x] **Have you named the issue title clearly and descriptively?**
- [x] **Have you searched for existing issues in the project to avoid duplicates?**

### Description

For now, this package has different modules with different features, some work offline and some online. I want to create one module for all the functions which can be used offline in one module in an optimal way. 

I have thought of some sneaky names
-visual.py
-support.py
-graph_utils.py
These kind of names, align with the theme of being sneaky. 

### Approach to Creating This Feature

- There are functions like copy_to_clipboard(), write(), plot() and a few other functions which can be used offline. 
- I I'll merge all these in one file, under the name you suggest.

### Benefits

- it'll make it sneaky
- code would be easily readable and manageable 
- less number of modules with more functionality.

Let me know your thoughts on this and also recommend changes if you feel like.

### Checklist
- [x] I have followed the issue title guidelines.
- [x] I have clearly described the feature and its approach.
- [x] I have explained the benefits of this feature.
- [x] I have added references or social links, where applicable.
- [x] I have provided additional context, if necessary.
- [x] I have read the GSSOC guidelines and understand the contribution process.
- [x] I have checked for existing issues and pull requests to avoid duplicates.

### LINKED ISSUE #187: Changes in Code:  Reduce Redundancy in Password Handling
### Files:
- **`clip.py`**
- **`show.py`**
- **`write.py`**

These above three files have "_password_" implemented in it, which introduces redundancy. Please refactor this code into a single file, `password.py`, that handles password validation and related logic.

> **Note**: Please ensure that this issue is addressed only after #186 has been resolved. Maintaining the order of these issues is essential.

### PR DESCRIPTION
**Pull request by tannuiscoding**
close #185 

it also closes #187 

changes I made

- added `offline.py` with all the offline usable functions
- reduced redundancy by adding `password.py`
- improved clip() and show() functions by reducing the same code

### CODE REVIEW

**Review by tannuiscoding — COMMENTED** [review]
looks nice to me

**Comment by this-is-yaash** [comment]
@tannuiscoding now that we have this combined into a single file, and the test cases are failing.

> it was written for separate files!

**Comment by this-is-yaash** [comment]
don't delete the old files (for now)
let's keep it

we'll raise the "test case" issue for that, then we'll remove it from the project!

**Comment by this-is-yaash** [comment]
also make separate PRs!
for each issue that you were assigned on

> it's better if you close this PR and make a new one!

**Comment by jindalpriyanshu101** [comment]
> also make separate PRs! for each issue that you were assigned on
> 
> > it's better if you close this PR and make a new one!

Simply merge this PR as `level-2` as it solves two level1 issues. It'll save some time.

**Pull request closed without merging**
