### PR TITLE
Feature request: Jekyll Static site

### PR DESCRIPTION
**Pull request by yashksaini-coder**
### Title of the Pull Request
- [X] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #72 

### Description
I have created & add necessary config files `yaml` & `HTML` for basic site structure. the main content that will be deployed is the `README.md` It is very easy to update & can be automate directly using the **Pages** settings in the repository. 

you just have to choose ***Deploy from branch*** add select the main branch. The action workflow is automatically generated & will build & deploy a Jekyll theme static-site on its own.

### Type of change

What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [X] My code follows the code style of this project.
- [X] I have followed the contribution guidelines
- [X] I have performed a self-review of my own code.
- [X] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [X] I have resolved all merge conflicts.

---

@this-is-yaash @Wahid7852 @jindalpriyanshu101 review this PR and add labels to it.

### CODE REVIEW

**Review by Wahid7852 — APPROVED** [review]
LGTM

**Review by jindalpriyanshu101 — APPROVED** [review]
I was forced to say, LGTM!

**Review by ShashwatAgrawal20 — APPROVED** [review]
LGTM!

image

**Comment by Hemu21** [comment]
@jindalpriyanshu101  @Wahid7852  @ShashwatAgrawal20  I am one of the program manager. level 2 is needed not the level 3 for this. I hope you understand. Can you please update the level label

**Comment by this-is-yaash** [comment]
> @jindalpriyanshu101 @Wahid7852 @ShashwatAgrawal20 I am one of the program manager. level 2 is needed not the level 3 for this. I hope you understand. Can you please update the level label

Yeah, sure!
Thanks for pointing out!

**Pull request merged**
