### PR TITLE
Add grab function to retrieve clipboard content

### PR DESCRIPTION
**Pull request by RManasvi**
Enhanced error handling and logging in the grab function

### Title of the Pull Request
- [x] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #<issue number>

### Type of change

What sort of changes have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Wahid7852** [comment]
Can you mention which issue is the PR targetting?

**Review by Wahid7852 — COMMENTED** [review]
Hi @RManasvi, I see you've only added logging to the grab function which was quite unnecessary. Would you mind telling me whats on your mind?

**Comment by ShashwatAgrawal20** [comment]
@RManasvi can you please change the title, I don't think the code only does what the title says.

**Comment by ShashwatAgrawal20** [comment]
possible duplicate of #88

**Comment by ShashwatAgrawal20** [comment]
There's no issue related to this PR. Closing this as not planned.

**Pull request closed without merging**
