### PR TITLE
Feature: checker for xcliip()

### PR DESCRIPTION
**Pull request by tannuiscoding**
Checking if Xclip is installed or not

### Related Issue
Closes: #44

### Description

this contribution is made under GSsoc'24ext.

### Type of change

What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Review by Wahid7852 — APPROVED** [review]
lgtm

**Comment by Wahid7852** [comment]
Hi @tannuiscoding, kindly amend your commit name and f-push it

**Review by jindalpriyanshu101 — APPROVED** [review]
LGTM, Approved.

**Review by this-is-yaash — APPROVED** [review]
LGTM! great job.

**Review by ShashwatAgrawal20 — APPROVED** [review]
LGTM! 

SHIP IT!

**Pull request merged**
