### PR TITLE
Static Site Update: GitHub Pages 

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Fixes: #121 

This pull request focuses on adding comprehensive documentation for the `sneaky-package` project, including contribution guidelines, installation instructions, usage examples, and an updated documentation site configuration.

Documentation Additions:

* [`docs/contributing.md`](diffhunk://#diff-419d79ae7d440d49b3fa5fa7739f5f3a359e3ca42c3fa942e5604ae3474eb35bR1-R116): Added detailed contribution guidelines, including steps for setting up the development environment, identifying issues, making changes, and submitting contributions.
* [`docs/index.md`](diffhunk://#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R1-R9): Created an index page to guide users through the documentation, including links to usage, installation, and contribution guidelines.
* [`docs/installation.md`](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56R1-R50): Provided a complete installation guide, including prerequisites, installation steps, verification, and troubleshooting tips.
* [`docs/usage.md`](diffhunk://#diff-72376d0b487d7231cf31959bf266f6aea098e899743bae02e36d176cef4db476R1-R44): Added usage instructions, including installation, basic usage, advanced features, and licensing information.

Documentation Site Configuration:

* [`mkdocs.yml`](diffhunk://#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R1-R30): Configured the documentation site with a theme, navigation structure, and Markdown extensions for better readability and usability.

---

This is before:- 

[sneaky-package-Before.webm](https://github.com/user-attachments/assets/fbc1e9f0-700b-4e2e-ab2b-47312ecbadcd)

<br>

AND after the MKdocs:- 

[sneaky-package-After.webm](https://github.com/user-attachments/assets/ab0f90c8-2e19-424f-9f18-7f7a9009663f)

---

Hi @this-is-yaash @jindalpriyanshu101 I have build the Documentation site with Github Pages deployment using MKDocs. Review this PR and add proper labels to it.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@this-is-yaash can you review this PR, add proper labels to it.

**Comment by jindalpriyanshu101** [comment]
Hey @yashksaini-coder, its really impressive, but can't you use some minimalist kind of theme? as the current one feels a little bit over in terms of colors..

**Comment by yashksaini-coder** [comment]
> Hey @yashksaini-coder, its really impressive, but can't you use some minimalist kind of theme? as the current one feels a little bit over in terms of colors..

yes I agree with you I was looking for github-dark theme, but for testing purposes this once was the best I could find on internet

**Comment by yashksaini-coder** [comment]
I will keep looking for the themes, and will share samples in the meantime @jindalpriyanshu101

**Comment by jindalpriyanshu101** [comment]
Well then, Everything looks good to me. However, changing theme to something blackish will be appreciated. Great Work tho. ;D

**Review by jindalpriyanshu101 — APPROVED** [review]

**Review by this-is-yaash — COMMENTED** [review]
Everything is good.
We still have to update the home page (`index.md`)of the site.

Use your own approach to add contents in the home page and make a PR. 
We'll get it merged!

**Comment by yashksaini-coder** [comment]
> Everything is good. We still have to update the home page (`index.md`)of the site.
> 
> Use your own approach to add contents in the home page and make a PR. We'll get it merged!

Understood, let me cook

**Review by ShashwatAgrawal20 — APPROVED** [review]
LGTM! 

shipit

**Comment by yashksaini-coder** [comment]
@this-is-yaash check my forked version link now I have added new docs & changes the theme to dark style

**Pull request merged**
