### PR TITLE
create Contributing.md

### PR DESCRIPTION
**Pull request by kartikey369-ind**
created Contributing.md file which gives steps for the contributors on how to contribute in this repository

### CODE REVIEW

**Comment by jindalpriyanshu101** [comment]
Please mention the issue number you've solved. it must be linked.

https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by kartikey369-ind** [comment]
> Please mention the issue number you've solved. it must be linked.
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

https://github.com/this-is-yaash/sneaky-package/issues/38

**Comment by kartikey369-ind** [comment]
Resolves #38

**Comment by jindalpriyanshu101** [comment]
> I can clearly see that the content is plagiarized, as I've mentioned before. Please conduct thorough research and work on the issue instead of copy-pasting GPT answers. #38
> 
> **Read**: [#38 (comment)](https://github.com/AmateursLeague/sneaky-package/issues/38#issuecomment-2388477767)


Need updates as directed. @kartikey369-ind

**Pull request closed without merging**
