### PR TITLE
✅ Website Enhancement

### PR DESCRIPTION
**Pull request by yashksaini-coder**
### Summary

I have update the main logo and also fixed some routing bugs. 

[how-it-works-bugfix.webm](https://github.com/user-attachments/assets/1df67f6e-5630-488b-b70d-5801a88d9d32)

@this-is-yaash kindly review this PR, and assign it to me with proper labels

### CODE REVIEW

**Comment by this-is-yaash** [comment]
@yashksaini-coder please share the screenshot of your implementation!

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder please share the screenshot of your changes!

image

**Review by this-is-yaash — APPROVED** [review]
LGTM!

**Review by this-is-yaash — COMMENTED** [review]
Please resolve the conflicts!

**Comment by this-is-yaash** [comment]
@yashksaini-coder increased lvl due to pointing out routing error in the site!
(Which has gone unnoticed!)
good work!

**Pull request merged**
