### PR TITLE
Docs: PyPi Setup & Deploy #68

### PR DESCRIPTION
**Pull request by yasheela-alla**
### Related Issue

Closes: #68 

### Description
This Documentation provides a comprehensive overview on how to set up and deploy a Python package to the Python Package Index (PyPI).

### Checklist

- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation.
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by yasheela-alla** [comment]
@this-is-yaash Hi Sir, Please review and Let me know if i need to make any changes :)

**Comment by this-is-yaash** [comment]
@yasheela-alla LGTM! 
We'll merge it shortly after the mentors approve this!

**Comment by ShashwatAgrawal20** [comment]
LGTM! 

shipit

**Review by ShashwatAgrawal20 — APPROVED** [review]
LGTM! 

shipit

**Review by Wahid7852 — APPROVED** [review]
lgtm

**Comment by yasheela-alla** [comment]
Thank you :))

**Pull request merged**
