### PR TITLE
install.sh script added to install the required dependencies.

### PR DESCRIPTION
**Pull request by Aum8**
Description:

This pull request adds a new script, install.sh, located in the project's root directory. This script automates the installation process for the prerequisites outlined in the "Review the prerequisites & Installation Section" in PyPi_setup.md

Installation in windows using git bash:
Screenshot 2024-10-26 233436

Installation in Ubuntu:
image

Issue Reference:
Solves issue #157

### CODE REVIEW

**Comment by Wahid7852** [comment]
have you considered the case where the user runs the script on linux

**Comment by techy4shri** [comment]
Kindly follow the PR template @Aum8 and then wait for further review.

**Comment by Aum8** [comment]
> Kindly follow the PR template @Aum8 and then wait for further review. And include the screenshot of installion success in both Windows and Linux or any othe OS you have tried for check in the screenshot section.

Thank you! Updated the description.

**Review by this-is-yaash — APPROVED** [review]
LGTM!✅

**Review by this-is-yaash — APPROVED** [review]
LGTM!✅

**Comment by this-is-yaash** [comment]
@Wahid7852 @techy4shri hey, the PR template is not working right now.
Idk why, so I'm working on that!

---
so far the script looks good and executing the operations perfectly, so let's merge it!

**Pull request merged**
